#dependabot configuration for NPM

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
    groups:
      react-deps:
        patterns:
          - "react"
          - "react-dom"
      emotion:
        patterns:
          - "@emotion*"
      mui:
        patterns:
          - "@mui*"
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
